name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem
        chmod 600 github-ec2.pem

        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
        
        echo " Entrando al servidor..."
        export NVM_DIR="$HOME/.nvm"

        # Cargar nvm si existe
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

        # Instalar nvm si no existe
        if ! command -v nvm &> /dev/null; then
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          source ~/.bashrc
        fi

        nvm install 18
        nvm use 18

        # Instalar pm2 si no existe
        if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
        fi

        REPO_URL="https://github.com/ARSW2026-JDC/Traffic-Simulator-Backend"
        BRANCH="main"
        REPO_DIR="$HOME/github-aws-ec2"

        if [ -d "$REPO_DIR/.git" ]; then
          cd "$REPO_DIR"
          git pull origin "$BRANCH"
        else
          git clone "$REPO_URL" "$REPO_DIR"
          cd "$REPO_DIR"
        fi

        echo "Instalando dependencias..."
        npm install

        echo "Build de NestJS..."
        npm run build

        echo "Deploy con PM2..."

        pm2 describe nest-app > /dev/null
        if [ $? -eq 0 ]; then
          pm2 restart nest-app
        else
          pm2 start dist/main.js --name nest-app
        fi

        pm2 save
        '